const us = document.querySelector('.top-percent')
const midTop = document.querySelector('.eightyth-percentile')
const mid = document.querySelector('.sixtyth-percentile')
const midBottom =document.querySelector('.fourtyth-percentile')
const bottom = document.querySelector('.twentyth-percentile')

// check if element exists
if (document.body.contains(us)) {

us.addEventListener('click', function(){
 document.querySelector('#US').classList.add('top-twenty')
 document.querySelector('#CA').classList.add('top-twenty')
 document.querySelector('#MX').classList.add('top-twenty')
 document.querySelector('#CN').classList.add('top-twenty')
 document.querySelector('#GE').classList.add('top-twenty')
 document.querySelector('#JP').classList.add('top-twenty')
 document.querySelector('#AU').classList.add('top-twenty')
 document.querySelector('#ES').classList.add('top-twenty')
 document.querySelector('#FR').classList.add('top-twenty')
 document.querySelector('#RU').classList.add('top-twenty')
 document.querySelector('#KR').classList.add('top-twenty')
 document.querySelector('#BR').classList.add('top-twenty')
 document.querySelector('#IT').classList.add('top-twenty')
 document.querySelector('#IN').classList.add('top-twenty')
  document.querySelector('#DE').classList.add('top-twenty')
    document.querySelector('#GB').classList.add('top-twenty')
})

midTop.addEventListener('click', function(){
 document.querySelector('#ID').classList.add('eighty-percent')
 document.querySelector('#TR').classList.add('eighty-percent')
 document.querySelector('#NL').classList.add('eighty-percent')
 document.querySelector('#CH').classList.add('eighty-percent')
 document.querySelector('#SA').classList.add('eighty-percent')
 document.querySelector('#AR').classList.add('eighty-percent')
 document.querySelector('#SE').classList.add('eighty-percent')
 document.querySelector('#TW').classList.add('eighty-percent')
})

mid.addEventListener('click', function(){
 document.querySelector('#IR').classList.add('sixty-percent')
 document.querySelector('#PE').classList.add('sixty-percent')
 document.querySelector('#KZ').classList.add('sixty-percent')
 document.querySelector('#KG').classList.add('sixty-percent')
 document.querySelector('#CZ').classList.add('sixty-percent')
 document.querySelector('#RO').classList.add('sixty-percent')
 document.querySelector('#NZ').classList.add('sixty-percent')
 document.querySelector('#IQ').classList.add('sixty-percent')
 document.querySelector('#QA').classList.add('sixty-percent')
 document.querySelector('#DZ').classList.add('sixty-percent')
 document.querySelector('#HU').classList.add('sixty-percent')
 document.querySelector('#KW').classList.add('sixty-percent')
 document.querySelector('#PR').classList.add('sixty-percent')
 document.querySelector('#AO').classList.add('sixty-percent')
 document.querySelector('#EC').classList.add('sixty-percent')
 document.querySelector('#MA').classList.add('sixty-percent')
 document.querySelector('#PL').classList.add('sixty-percent')
 document.querySelector('#BE').classList.add('sixty-percent')
 document.querySelector('#IQ').classList.add('sixty-percent')
 document.querySelector('#TH').classList.add('sixty-percent')
 document.querySelector('#NG').classList.add('sixty-percent')
 document.querySelector('#AT').classList.add('sixty-percent')
 document.querySelector('#NO').classList.add('sixty-percent')
 document.querySelector('#VE').classList.add('sixty-percent')
 document.querySelector('#AE').classList.add('sixty-percent')
 document.querySelector('#EG').classList.add('sixty-percent')
 document.querySelector('#ZA').classList.add('sixty-percent')
 document.querySelector('#MY').classList.add('sixty-percent')
 document.querySelector('#IL').classList.add('sixty-percent')
 document.querySelector('#DK').classList.add('sixty-percent')
 document.querySelector('#SG').classList.add('sixty-percent')
 document.querySelector('#CO').classList.add('sixty-percent')
 document.querySelector('#PH').classList.add('sixty-percent')
 document.querySelector('#PK').classList.add('sixty-percent')
 document.querySelector('#CL').classList.add('sixty-percent')
 document.querySelector('#IE').classList.add('sixty-percent')
 document.querySelector('#FI').classList.add('sixty-percent')
 document.querySelector('#PT').classList.add('sixty-percent')
 document.querySelector('#GR').classList.add('sixty-percent')
 document.querySelector('#BD').classList.add('sixty-percent')
 document.querySelector('#VN').classList.add('sixty-percent')
 document.querySelector('#BA').classList.add('sixty-percent')
})

midBottom.addEventListener('click', function(){
 document.querySelector('#UA').classList.add('fourty-percent')
 document.querySelector('#SK').classList.add('fourty-percent')
 document.querySelector('#SD').classList.add('fourty-percent')
 document.querySelector('#LK').classList.add('fourty-percent')
 document.querySelector('#CU').classList.add('fourty-percent')
 document.querySelector('#OM').classList.add('fourty-percent')
 document.querySelector('#DO').classList.add('fourty-percent')
 document.querySelector('#UZ').classList.add('fourty-percent')
 document.querySelector('#MM').classList.add('fourty-percent')
 document.querySelector('#GT').classList.add('fourty-percent')
 document.querySelector('#KE').classList.add('fourty-percent')
 document.querySelector('#ET').classList.add('fourty-percent')
 document.querySelector('#LU').classList.add('fourty-percent')
 document.querySelector('#BY').classList.add('fourty-percent')
 document.querySelector('#UY').classList.add('fourty-percent')
 document.querySelector('#AZ').classList.add('fourty-percent')
 document.querySelector('#PA').classList.add('fourty-percent')
 document.querySelector('#CR').classList.add('fourty-percent')
 document.querySelector('#HR').classList.add('fourty-percent')
 document.querySelector('#LB').classList.add('fourty-percent')
 document.querySelector('#TZ').classList.add('fourty-percent')
 document.querySelector('#TN').classList.add('fourty-percent')
 document.querySelector('#SI').classList.add('fourty-percent')
 document.querySelector('#LT').classList.add('fourty-percent')
 document.querySelector('#BG').classList.add('fourty-percent')

})

bottom.addEventListener('click', function(){
 document.querySelector('#GH').classList.add('twenty-percent')
 document.querySelector('#JO').classList.add('twenty-percent')
 document.querySelector('#TM').classList.add('twenty-percent')
 document.querySelector('#RS').classList.add('twenty-percent')
 document.querySelector('#YE').classList.add('twenty-percent')
 document.querySelector('#CG').classList.add('twenty-percent')
 document.querySelector('#BO').classList.add('twenty-percent')
 document.querySelector('#CI').classList.add('twenty-percent')
 document.querySelector('#CM').classList.add('twenty-percent')
 document.querySelector('#TT').classList.add('twenty-percent')
 document.querySelector('#PY').classList.add('twenty-percent')
 document.querySelector('#LV').classList.add('twenty-percent')
 document.querySelector('#UG').classList.add('twenty-percent')
 document.querySelector('#SV').classList.add('twenty-percent')
 document.querySelector('#EE').classList.add('twenty-percent')
 document.querySelector('#ZM').classList.add('twenty-percent')
 document.querySelector('#NP').classList.add('twenty-percent')
 document.querySelector('#HN').classList.add('twenty-percent')
 document.querySelector('#CY').classList.add('twenty-percent')
 document.querySelector('#AF').classList.add('twenty-percent')
 document.querySelector('#GA').classList.add('twenty-percent')
 document.querySelector('#BN').classList.add('twenty-percent')
 document.querySelector('#IS').classList.add('twenty-percent')
 document.querySelector('#IS').classList.add('twenty-percent')
 document.querySelector('#KH').classList.add('twenty-percent')
 document.querySelector('#GE').classList.add('twenty-percent')
 document.querySelector('#MZ').classList.add('twenty-percent')
 document.querySelector('#BW').classList.add('twenty-percent')
 document.querySelector('#SN').classList.add('twenty-percent')
 document.querySelector('#GQ').classList.add('twenty-percent')
 document.querySelector('#ZW').classList.add('twenty-percent')
 document.querySelector('#CD').classList.add('twenty-percent')
 document.querySelector('#TD').classList.add('twenty-percent')
 document.querySelector('#JM').classList.add('twenty-percent')
 document.querySelector('#SS').classList.add('twenty-percent')
 document.querySelector('#AL').classList.add('twenty-percent')
 document.querySelector('#NA').classList.add('twenty-percent')
 document.querySelector('#MU').classList.add('twenty-percent')
 document.querySelector('#BF').classList.add('twenty-percent')
 document.querySelector('#ML').classList.add('twenty-percent')
 document.querySelector('#MN').classList.add('twenty-percent')
 document.querySelector('#LA').classList.add('twenty-percent')
 document.querySelector('#NI').classList.add('twenty-percent')
 document.querySelector('#AM').classList.add('twenty-percent')
 document.querySelector('#MK').classList.add('twenty-percent')
 document.querySelector('#MG').classList.add('twenty-percent')
 document.querySelector('#MT').classList.add('twenty-percent')
 document.querySelector('#BJ').classList.add('twenty-percent')
 document.querySelector('#TJ').classList.add('twenty-percent')
 document.querySelector('#HT').classList.add('twenty-percent')
 document.querySelector('#BS').classList.add('twenty-percent')
 document.querySelector('#NE').classList.add('twenty-percent')
 document.querySelector('#MD').classList.add('twenty-percent')
 document.querySelector('#RW').classList.add('twenty-percent')
 document.querySelector('#KG').classList.add('twenty-percent')
 // document.querySelector('#KV').classList.add('twenty-percent')
 document.querySelector('#GN').classList.add('twenty-percent')
 document.querySelector('#SO').classList.add('twenty-percent')
 document.querySelector('#BM').classList.add('twenty-percent')
document.querySelector('#LI').classList.add('twenty-percent')
document.querySelector('#SR').classList.add('twenty-percent')
document.querySelector('#MR').classList.add('twenty-percent')
document.querySelector('#SL').classList.add('twenty-percent')
document.querySelector('#ME').classList.add('twenty-percent')
document.querySelector('#FJ').classList.add('twenty-percent')
document.querySelector('#TG').classList.add('twenty-percent')
document.querySelector('#SZ').classList.add('twenty-percent')
document.querySelector('#BB').classList.add('twenty-percent')
document.querySelector('#MW').classList.add('twenty-percent')
document.querySelector('#AD').classList.add('twenty-percent')
document.querySelector('#GY').classList.add('twenty-percent')
document.querySelector('#BI').classList.add('twenty-percent')
document.querySelector('#MV').classList.add('twenty-percent')
document.querySelector('#FO').classList.add('twenty-percent')
document.querySelector('#GL').classList.add('twenty-percent')
document.querySelector('#LS').classList.add('twenty-percent')
document.querySelector('#LR').classList.add('twenty-percent')
document.querySelector('#CV').classList.add('twenty-percent')
document.querySelector('#CF').classList.add('twenty-percent')
document.querySelector('#BZ').classList.add('twenty-percent')
document.querySelector('#DJ').classList.add('twenty-percent')
document.querySelector('#SC').classList.add('twenty-percent')
document.querySelector('#TL').classList.add('twenty-percent')
document.querySelector('#LC').classList.add('twenty-percent')
document.querySelector('#AG').classList.add('twenty-percent')
document.querySelector('#SB').classList.add('twenty-percent')
document.querySelector('#GW').classList.add('twenty-percent')
document.querySelector('#GM').classList.add('twenty-percent')
document.querySelector('#GD').classList.add('twenty-percent')
document.querySelector('#KN').classList.add('twenty-percent')
document.querySelector('#VU').classList.add('twenty-percent')
document.querySelector('#LY').classList.add('twenty-percent')
document.querySelector('#VC').classList.add('twenty-percent')
document.querySelector('#KM').classList.add('twenty-percent')
document.querySelector('#DM').classList.add('twenty-percent')
document.querySelector('#TO').classList.add('twenty-percent')
document.querySelector('#ST').classList.add('twenty-percent')
document.querySelector('#PG').classList.add('twenty-percent')
document.querySelector('#GF').classList.add('twenty-percent')
document.querySelector('#BT').classList.add('twenty-percent')
document.querySelector('#KP').classList.add('twenty-percent')
// document.querySelector('#PW').classList.add('twenty-percent')
// document.querySelector('#MH').classList.add('twenty-percent')
// document.querySelector('#KI').classList.add('twenty-percent')
// document.querySelector('#TV').classList.add('twenty-percent')
document.querySelector('#NC').classList.add('twenty-percent')
document.querySelector('#ER').classList.add('twenty-percent')
document.querySelector('#SY').classList.add('twenty-percent')
 document.querySelector('#EH').classList.add('twenty-percent')
 })

 } // close if element exists

 const circle = document.querySelector('.circle')
  const secondCircle = document.querySelector('.second-circle')
 // const body = document.querySelector('body')
 // const height = body.clientHeight
 const body = document.querySelector('body')
const height = body.clientHeight

 var percentage = 0

 // circle.style.top = ((window.innerHeight / height)) * 83 + '%'
// window.addEventListener('resize', function(){ })
 window.addEventListener('scroll', function() {
   percentage = ((this.pageYOffset + this.innerHeight) / height) * 83
   console.log('window height: ' + (this.pageYOffset + this.innerHeight))
   console.log('window height: ' + height)
   console.log(percentage.toFixed())
   circle.style.top = percentage.toFixed() + '%'
   secondCircle.style.top = percentage.toFixed() + '%'
   if (percentage <= 34) {
     secondCircle.style.opacity = 1
   } else if (percentage >= 34 && percentage <= 46) {
     secondCircle.style.opacity = 0
    //  secondCircle.style.backgroundColor = 'red'
    //  secondCircle.style.cssText = 'opacity:0; background-color:red;'
   } else if (percentage >= 46 && percentage <= 58) {
     secondCircle.style.opacity = 1
   } else if (percentage >= 58 && percentage <=72) {
     circle.style.opacity = 1
     secondCircle.style.opacity= 0
   }
   else if (percentage >= 72 && percentage <=83) {
     secondCircle.style.opacity = 0
     circle.style.opacity= 0
   }


 })
